# Save the file as setting_vars.py and add values to the fields below.
# Do not edit this file directly. It will be commited to the repository.
# Add all keys and passwords to setting_vars.py

# SECRET_KEY
PROJ_SECRET_KEY = 'yp^y&lt&320%%nr02gp-bkl%7y3g^c+z1sme3#5f+86_az=bb*'
