# Save the file as setting_vars.py and add values to the fields below.
# Do not edit this file directly. It will be commited to the repository.
# Add all keys and passwords to setting_vars.py

# SECRET_KEY
PROJ_SECRET_KEY = some_key

# JWT_SECRET
JWT_SECRET = some_key

# List of IP addresses for ALLOWED_HOSTS
IP_ADDRESS_LIST = [some_list]

# List of Hostnames for ALLOWED_HOSTS
HOSTNAME_LIST = [some_list]
